version: '3.9'

services:
  neo4j:
    image: neo4j:latest
    volumes:
      - ./neo4jDB:/data
    container_name: neo4j-db
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password