name: build project

on: [push, pull_request]

jobs:
  run:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Run Tests
        run: ./gradlew clean test

      - if: matrix.os == 'ubuntu-latest' # Container action is only supported on Linux
        name: Run Test Coverage
        run: ./gradlew jacocoTestReport

      - if: matrix.os == 'ubuntu-latest'
        name: Jacoco Code Coverage Report
        uses: cicirello/jacoco-badge-generator@v2.8.0
        with:
          generate-branches-badge: true
          jacoco-csv-file: lib/build/jacoco/report.csv

      - if: github.event_name == "pull_request"
        name: Jacoco Test Coverage Verification
        run: ./gradlew jacocoTestCoverageVerification
